spring:
  application:
    name: mealweb
management:
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  level:
    br.com.topi.mealweb: debug

server:
  port: 5000
